# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/mr418/Desktop/ece350project/project.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mr418/Desktop/ece350project/project.cache/wt [current_project]
set_property parent.project_path C:/Users/mr418/Desktop/ece350project/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/mr418/Desktop/ece350project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {{C:/Users/mr418/Desktop/ece350project/processor/Test Files/Memory Files/test.mem}}
read_verilog -library xil_defaultlib {
  C:/Users/mr418/Desktop/ece350project/processor/DP_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/DX_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/FD_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/MW_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/PC_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/PW_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/RAM.v
  C:/Users/mr418/Desktop/ece350project/processor/ROM.v
  C:/Users/mr418/Desktop/ece350project/processor/Wrapper.v
  C:/Users/mr418/Desktop/ece350project/processor/Wrapper_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/XM_latch.v
  C:/Users/mr418/Desktop/ece350project/processor/alu.v
  C:/Users/mr418/Desktop/ece350project/processor/alu_personal_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/alu_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/and_bit.v
  C:/Users/mr418/Desktop/ece350project/processor/and_bit_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/bypass_ctrl.v
  C:/Users/mr418/Desktop/ece350project/processor/cla_32.v
  C:/Users/mr418/Desktop/ece350project/processor/cla_32_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/cla_8.v
  C:/Users/mr418/Desktop/ece350project/processor/cla_8_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/counter.v
  C:/Users/mr418/Desktop/ece350project/processor/counter_5.v
  C:/Users/mr418/Desktop/ece350project/processor/counter_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/dffe_ref.v
  C:/Users/mr418/Desktop/ece350project/processor/div.v
  C:/Users/mr418/Desktop/ece350project/processor/div_control.v
  C:/Users/mr418/Desktop/ece350project/processor/full_comparator.v
  C:/Users/mr418/Desktop/ece350project/processor/full_comparator_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/isa_decoder.v
  C:/Users/mr418/Desktop/ece350project/processor/lshift.v
  C:/Users/mr418/Desktop/ece350project/processor/lshift_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/mult.v
  C:/Users/mr418/Desktop/ece350project/processor/mult_control.v
  C:/Users/mr418/Desktop/ece350project/processor/mult_control_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/mult_overflow.v
  C:/Users/mr418/Desktop/ece350project/processor/multdiv.v
  C:/Users/mr418/Desktop/ece350project/processor/multdiv_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_2.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_2_1bit.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_2_64b.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_2_65b.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_32.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_32_1bit.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_4.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_4_1bit.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_8.v
  C:/Users/mr418/Desktop/ece350project/processor/mux_8_1bit.v
  C:/Users/mr418/Desktop/ece350project/processor/not_bit.v
  C:/Users/mr418/Desktop/ece350project/processor/not_bit_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/or_bit.v
  C:/Users/mr418/Desktop/ece350project/processor/or_bit_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/processor.v
  C:/Users/mr418/Desktop/ece350project/processor/reg_32.v
  C:/Users/mr418/Desktop/ece350project/processor/reg_32_div.v
  C:/Users/mr418/Desktop/ece350project/processor/reg_64.v
  C:/Users/mr418/Desktop/ece350project/processor/reg_65.v
  C:/Users/mr418/Desktop/ece350project/processor/reg_pc.v
  C:/Users/mr418/Desktop/ece350project/processor/regfile.v
  C:/Users/mr418/Desktop/ece350project/processor/regfile_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/rshift.v
  C:/Users/mr418/Desktop/ece350project/processor/rshift_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/sr.v
  C:/Users/mr418/Desktop/ece350project/processor/sr_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/tff.v
  C:/Users/mr418/Desktop/ece350project/processor/tff_tb.v
  C:/Users/mr418/Desktop/ece350project/processor/two_bit_comparator.v
  C:/Users/mr418/Desktop/ece350project/servo/angle_decoder.v
  C:/Users/mr418/Desktop/ece350project/servo/sw_to_angle.v
  C:/Users/mr418/Desktop/ece350project/servo/Servo_interface.v
  C:/Users/mr418/Desktop/ece350project/servo/counter.v
  C:/Users/mr418/Desktop/ece350project/servo/comparator.v
  C:/Users/mr418/Desktop/ece350project/processor/dff32.v
}
read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_proc/ila_proc.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_proc/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_proc/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_proc/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_proc/ila_proc_ooc.xdc]

read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_reg/ila_reg.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_reg/ila_reg_ooc.xdc]

read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_servo/ila_servo.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_servo_ooc.xdc]

read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet C:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_2_1/ila_2.xci
set_property used_in_synthesis false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_2_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_2_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_2_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_2_1/ila_2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mr418/Desktop/ece350project/project.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files C:/Users/mr418/Desktop/ece350project/project.srcs/constrs_1/new/led.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
