# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/dte12/Documents/ECE350/ece350project/project.srcs/sources_1/ip/ila_reg/ila_reg.xci
# IP: The module: 'ila_reg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_reg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/dte12/Documents/ECE350/ece350project/project.srcs/sources_1/ip/ila_reg/ila_reg.xci
# IP: The module: 'ila_reg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/dte12/Documents/ECE350/ece350project/project.gen/sources_1/ip/ila_reg/ila_reg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_reg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
