# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_servo/ila_servo.xci
# IP: The module: 'ila_servo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_servo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/mr418/Desktop/ece350project/project.srcs/sources_1/ip/ila_servo/ila_servo.xci
# IP: The module: 'ila_servo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/mr418/Desktop/ece350project/project.gen/sources_1/ip/ila_servo/ila_servo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_servo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
